cca-ffodregamdi/running-hi-back

.github/workflows/gradle.yml
src/main/java/com/runninghi/adminpost/command/domain/aggregate/entity/ADMINPOST.java
src/main/java/com/runninghi/adminpost/command/domain/aggregate/entity/test.java
src/main/java/com/runninghi/adminpost/command/domain/aggregate/vo/WriterNoVO.java
src/main/java/com/runninghi/adminpost/command/domain/aggregate/vo/test.java
src/main/java/com/runninghi/keyword/command/domain/aggregate/entity/Keyword.java
src/main/java/com/runninghi/keyword/command/domain/aggregate/entity/test.java
src/main/java/com/runninghi/keywordofpost/command/domain/aggregate/entity/KeywordOfPost.java
src/main/java/com/runninghi/keywordofpost/command/domain/aggregate/entity/test.java
src/main/java/com/runninghi/keywordofpost/command/domain/aggregate/vo/AdminPostVO.java
src/main/java/com/runninghi/keywordofpost/command/domain/aggregate/vo/KeywordVO.java
src/main/java/com/runninghi/keywordofpost/command/domain/aggregate/vo/UserPostVO.java
src/main/java/com/runninghi/keywordofpost/command/domain/aggregate/vo/test.java
src/test/java/com/runninghi/RunninghiApplicationTests.java

* closed #13 
* closed #12 
* closed #14 
- 관리자 게시글 엔티티 생성, VO 생성
- 키워드 엔티티 생성, VO 생성
- 게시물 키워드 엔티티 생성, VO 생성

[Feature]-[ADMIN POST] [KEYWORD] [KEYWORD OF POST] 엔티티 설계

---

src/main/java/com/runninghi/feedback/command/domain/aggregate/entity/Feedback.java
src/main/java/com/runninghi/feedback/command/domain/aggregate/entity/test.java
src/main/java/com/runninghi/feedback/command/domain/aggregate/vo/FeedbackCategoryVO.java
src/main/java/com/runninghi/feedback/command/domain/aggregate/vo/FeedbackWriterVO.java
src/main/java/com/runninghi/feedback/command/domain/aggregate/vo/test.java
src/main/java/com/runninghi/image/command/domain/aggregate/entity/Image.java
src/main/java/com/runninghi/image/command/domain/aggregate/entity/test.java
src/main/java/com/runninghi/image/command/domain/aggregate/vo/AdminPostVO.java
src/main/java/com/runninghi/image/command/domain/aggregate/vo/UserPostVO.java
src/main/java/com/runninghi/image/command/domain/aggregate/vo/test.java
src/main/java/com/runninghi/userpost/command/domain/aggregate/entity/UserPost.java
src/main/java/com/runninghi/userpost/command/domain/aggregate/entity/test.java
src/main/java/com/runninghi/userpost/command/domain/aggregate/vo/UserVO.java
src/main/java/com/runninghi/userpost/command/domain/aggregate/vo/test.java
src/main/resources/db/data/data.sql

feature : [user post] [feedback] [image] 엔티티  & VO 생성

---

src/main/java/com/runninghi/comment/command/domain/aggregate/entity/Comment.java
src/main/java/com/runninghi/comment/command/domain/aggregate/entity/test.java
src/main/java/com/runninghi/comment/command/domain/aggregate/vo/CommentReportCntVO.java
src/main/java/com/runninghi/comment/command/domain/aggregate/vo/UserNoVO.java
src/main/java/com/runninghi/comment/command/domain/aggregate/vo/test.java
src/main/resources/db/data/data.sql

* closed #11  
- CommentReportCountVO 에는 추후 신고 횟수 관련 로직 추가할 예정입니다.
(ex. 10회 이상 신고 -> 블러처리)

feature : {comment} 엔티티 & VO 생성

---

src/main/java/com/runninghi/bookmark/command/domain/aggregate/entity/Bookmark.java
src/main/java/com/runninghi/bookmark/command/domain/aggregate/entity/test.java
src/main/java/com/runninghi/bookmark/command/domain/aggregate/vo/BookmarkVO.java
src/main/java/com/runninghi/bookmark/command/domain/aggregate/vo/test.java
src/main/java/com/runninghi/bookmarkfolder/command/domain/aggregate/entity/BookmarkFolder.java
src/main/java/com/runninghi/bookmarkfolder/command/domain/aggregate/entity/test.java
src/main/resources/db/data/data.sql

* closed #10 
- 즐겨찾기 복합키(폴더 번호, 게시글 번호) 사용합니다.

feature : {bookmark} {bookmarkfolder} 엔티티 & VO 생성

---

.github/workflows/gradle.yml
build.gradle
src/main/java/com/runninghi/bookmark/command/domain/aggregate/entity/Bookmark.java
src/main/java/com/runninghi/bookmarkfolder/command/application/dto/SaveFolderDTO.java
src/main/java/com/runninghi/bookmarkfolder/command/application/dto/test.java
src/main/java/com/runninghi/bookmarkfolder/command/application/service/SaveNewBookmarkFolderService.java
src/main/java/com/runninghi/bookmarkfolder/command/application/service/test.java
src/main/java/com/runninghi/bookmarkfolder/command/domain/aggregate/entity/BookmarkFolder.java
src/main/java/com/runninghi/bookmarkfolder/command/domain/exception/BookmarkFolderException.java
src/main/java/com/runninghi/bookmarkfolder/command/domain/exception/test.java
src/main/java/com/runninghi/bookmarkfolder/command/domain/repository/BookmarkFolderRepository.java
src/main/java/com/runninghi/bookmarkfolder/command/domain/repository/test.java
src/main/resources/db/data/data.sql
src/test/java/com/runninghi/RunninghiApplicationTests.java
src/test/java/com/runninghi/bookmarkfolder/command/application/service/SaveNewBookmarkFolderTests.java

* closed  #24
* closed  #25
* closed  #35
- 즐겨찾기 폴더 생성 후 저장
- 제목 20자 넘을 경우 예외처리
- Gradle assertJ dependency 추가
- **테스트 코드 작성 시 사용한 assertJ 관련 dependencies gradle 에 추가했습니다. 꼭! 확인해주세요.**

[Feature] - {bookmarkfolder} 새 즐겨찾기 폴더 생성, git action 오류 수정

---

src/main/java/com/runninghi/keyword/command/domain/aggregate/entity/Keyword.java

* closed #64 
회의 때 의논한 코드 컨벤션의 의거

[Refactor] - {KEYWORD} 엔터티 빌더 패턴 적용

---

src/main/java/com/runninghi/adminpost/command/domain/exception/test.java
src/main/java/com/runninghi/keyword/command/domain/exception/test.java
src/main/java/com/runninghi/keywordofpost/command/domain/aggregate/entity/KeywordOfPost.java
src/main/java/com/runninghi/keywordofpost/command/domain/aggregate/vo/KeywordVO.java
src/main/java/com/runninghi/keywordofpost/command/domain/aggregate/vo/UserPostVO.java
src/main/java/com/runninghi/keywordofpost/command/domain/exception/test.java

[Refactor] - {KEYWORD OF POST} 엔터티 빌더 패턴 적용

---

.github/workflows/gradle.yml
.gitmodules
build.gradle
src/main/resources/bootstrap.yml

* closed #47
* 민감 정보 노출을 방지하기 위해 spring config server 도입

spring cloud config

---

src/main/java/com/runninghi/bookmarkfolder/command/application/service/SaveNewBookmarkFolderService.java
src/main/java/com/runninghi/bookmarkfolder/command/domain/aggregate/vo/test.java
src/main/java/com/runninghi/bookmarkfolder/command/domain/exception/BookmarkFolderException.java
src/main/java/com/runninghi/bookmarkfolder/command/domain/repository/SaveFolderRepository.java
src/main/java/com/runninghi/bookmarkfolder/command/domain/service/FindBookmarkFolder.java
src/main/java/com/runninghi/bookmarkfolder/query/application/dto/FindFolderDTO.java
src/main/java/com/runninghi/bookmarkfolder/query/application/dto/test.java
src/main/java/com/runninghi/bookmarkfolder/query/application/service/FindBookmarkFolderImpl.java
src/main/java/com/runninghi/bookmarkfolder/query/application/service/test.java
src/main/java/com/runninghi/bookmarkfolder/query/infrastructure/repository/FindFolderRepository.java
src/main/java/com/runninghi/bookmarkfolder/query/infrastructure/repository/test.java
src/main/java/com/runninghi/bookmarkfolder/query/infrastructure/service/FindBookmarkFolder.java
src/main/java/com/runninghi/bookmarkfolder/query/infrastructure/service/test.java
src/test/java/com/runninghi/bookmarkfolder/command/application/service/SaveNewBookmarkFolderTests.java
src/test/java/com/runninghi/bookmarkfolder/query/application/service/FindBookmarkFolderTests.java

* closed #39 
* closed #40
폴더 번호로 특정 폴더 조회 기능

[Feature] - {Bookmark Folder} 폴더 조회 기능 구현

---

.github/workflows/gradle.yml
.gitignore

Setting/secrets jwt 설정

---

src/main/java/com/runninghi/bookmarkfolder/command/application/dto/request/CreateFolderRequest.java
src/main/java/com/runninghi/bookmarkfolder/command/application/dto/request/UpdateFolderRequest.java
src/main/java/com/runninghi/bookmarkfolder/command/application/service/CreateNewBookmarkFolderService.java
src/main/java/com/runninghi/bookmarkfolder/command/application/service/DeleteBookmarkFolderService.java
src/main/java/com/runninghi/bookmarkfolder/command/application/service/UpdateBookmarkFolderService.java
src/main/java/com/runninghi/bookmarkfolder/command/domain/service/BookmarkFolderDomainService.java
src/main/java/com/runninghi/bookmarkfolder/command/infrastructure/service/BookmarkFolderDomainServiceImpl.java
src/main/java/com/runninghi/bookmarkfolder/command/infrastructure/service/BookmarkFolderInfraService.java
src/main/java/com/runninghi/bookmarkfolder/query/application/service/FindBookmarkFolderService.java
src/main/java/com/runninghi/common/annotation/DomainService.java
src/test/java/com/runninghi/bookmarkfolder/command/application/service/CreateNewBookmarkFolderTests.java
src/test/java/com/runninghi/bookmarkfolder/command/application/service/DeleteBookmarkFolderTests.java
src/test/java/com/runninghi/bookmarkfolder/command/application/service/UpdateBookmarkFolderTests.java
src/test/java/com/runninghi/bookmarkfolder/query/application/service/FindBookmarkFolderTests.java

* closed #80
* closed #81
- infra, domain 서비스 수정했습니다. 잘못된 부분 있으면 바로 수정하겠습니다🤔
- - ### 인터페이스 참조 수정

feature : {bookmark folder} 즐겨찾기 폴더 수정 기능 

---

src/main/java/com/runninghi/bookmark/command/application/dto/request/CreateBookmarkRequest.java
src/main/java/com/runninghi/bookmark/command/application/dto/test.java
src/main/java/com/runninghi/bookmark/command/application/service/CreateBookmarkService.java
src/main/java/com/runninghi/bookmark/command/application/service/test.java
src/main/java/com/runninghi/bookmark/command/domain/aggregate/entity/Bookmark.java
src/main/java/com/runninghi/bookmark/command/domain/exception/test.java
src/main/java/com/runninghi/bookmark/command/domain/repository/BookmarkRepository.java
src/main/java/com/runninghi/bookmark/command/domain/repository/test.java
src/main/java/com/runninghi/bookmark/command/domain/service/BookmarkDomainService.java
src/main/java/com/runninghi/bookmark/command/domain/service/test.java
src/main/java/com/runninghi/bookmark/command/infrastructure/service/BookmarkInfraService.java
src/main/java/com/runninghi/bookmark/command/infrastructure/service/test.java
src/main/java/com/runninghi/common/annotation/DomainService.java
src/main/resources/db/data/data.sql
src/test/java/com/runninghi/bookmark/command/application/service/CreateBookmarkTests.java

* closed #49 
* closed #90 
- 존재하지 않는 게시물 번호 예러는 일단 주석처리해놨습니다!
- ### 인터페이스 참조 수정

feature : {bookmark} 즐겨찾기 추가 기능

---

src/test/java/com/runninghi/User/command/application/service/AdminServiceTest.java
src/test/java/com/runninghi/User/command/application/service/SignServiceTest.java
src/test/java/com/runninghi/User/command/application/service/UserServiceTest.java
src/test/java/com/runninghi/bookmark/command/application/service/CommandBookmarkServiceTests.java
src/test/java/com/runninghi/bookmark/query/application/service/QueryBookmarkServiceTests.java
src/test/java/com/runninghi/bookmarkfolder/command/application/service/CommandBookmarkFolderServiceTests.java
src/test/java/com/runninghi/bookmarkfolder/query/application/service/QueryBookmarkFolderServiceTests.java
src/test/java/com/runninghi/comment/command/application/service/CommandCommentServiceTests.java
src/test/java/com/runninghi/comment/query/application/service/QueryCommentServiceTests.java
src/test/java/com/runninghi/common/GpxParserTest.java
src/test/java/com/runninghi/feedback/command/service/FeedbackReplyServiceTests.java
src/test/java/com/runninghi/feedback/command/service/FeedbackServiceTests.java
src/test/java/com/runninghi/jwt/exception/JwtExceptionResponseTest.java

* closed #110 
@numerical43 
@fakerdeft 
@Subak-Uncle 
혹시 틀린 거 없는 지 확인 한 번씩 부탁드립니다!!

refactor : 테스트 display 형식 통일

---

src/main/java/com/runninghi/AdminInitializer.java
src/main/java/com/runninghi/RunninghiApplication.java
src/main/java/com/runninghi/configuration/jwt/JwtAuthenticationFilter.java
src/main/java/com/runninghi/configuration/jwt/TokenProvider.java
src/main/java/com/runninghi/user/command/domain/aggregate/entity/User.java
src/test/java/com/runninghi/jwt/exception/JwtExceptionResponseTest.java

[REFACTORING][SETTING] - {USER} USER Entity 수정

---

src/main/java/com/runninghi/keyword/command/application/controller/KeywordCommandController.java
src/main/java/com/runninghi/keyword/command/application/service/KeywordCommandService.java
src/main/java/com/runninghi/keyword/command/domain/repository/KeywordCommandRepository.java
src/main/java/com/runninghi/keyword/command/domain/service/KeywordCommandDomainService.java
src/main/java/com/runninghi/keyword/query/application/controller/KeywordQueryController.java
src/main/java/com/runninghi/keyword/query/application/service/KeywordQueryService.java
src/main/java/com/runninghi/keyword/query/infrastructure/repository/KeywordQueryRepository.java
src/test/java/com/runninghi/keyword/command/application/service/KeywordCommandServiceTest.java
src/test/java/com/runninghi/keyword/query/application/service/KeywordQueryServiceTest.java

* closed #123
* closed #124  
파일 명칭 통일 및 Mapping URL 수정

[Rename] - {KEYWORD} 파일 명칭 변경 및 url 수정

---

src/main/java/com/runninghi/comment/command/application/dto/request/DeleteCommentRequest.java
src/main/java/com/runninghi/comment/command/application/service/CommentCommandService.java
src/main/java/com/runninghi/comment/command/domain/service/CommentCommandDomainService.java
src/main/java/com/runninghi/comment/command/infrastructure/service/CommentCommandInfraService.java
src/main/java/com/runninghi/comment/query/application/service/CommentQueryService.java
src/main/java/com/runninghi/common/handler/BookmarkFolder/ExceptionResponseHandler.java
src/test/java/com/runninghi/comment/command/application/service/CommentCommandServiceTests.java

[Feat] - {COMMENT} 댓글 삭제 기능 구현

---

src/main/java/com/runninghi/bookmark/command/domain/repository/BookmarkRepository.java
src/main/java/com/runninghi/comment/command/application/dto/request/UpdateCommentRequest.java
src/main/java/com/runninghi/comment/command/application/service/CommentCommandService.java
src/main/java/com/runninghi/comment/command/domain/aggregate/entity/Comment.java
src/test/java/com/runninghi/comment/command/application/service/CommentCommandServiceTests.java

[Feat] - {COMMENT} 댓글 수정 기능 구현

---

build.gradle
src/main/java/com/runninghi/keyword/command/application/dto/request/KeywordCreateRequest.java
src/main/java/com/runninghi/keyword/command/application/dto/request/KeywordUpdateRequest.java
src/main/java/com/runninghi/keyword/command/application/dto/response/KeywordUpdateResponse.java
src/main/java/com/runninghi/keyword/command/application/service/KeywordCommandService.java
src/main/java/com/runninghi/keyword/command/domain/aggregate/entity/Keyword.java
src/main/java/com/runninghi/keyword/query/application/dto/response/FindKeywordResponse.java
src/main/java/com/runninghi/keyword/query/application/service/KeywordQueryService.java
src/main/resources/db/data/data.sql
src/test/java/com/runninghi/keyword/command/application/service/KeywordCommandServiceTest.java
src/test/java/com/runninghi/keyword/query/application/service/KeywordQueryServiceTest.java

[Feature] - {KEYWORD} update

---

src/test/java/com/runninghi/bookmark/command/application/service/BookmarkCommandServiceTests.java
src/test/java/com/runninghi/bookmark/query/application/service/BookmarkQueryServiceTests.java
src/test/java/com/runninghi/bookmarkfolder/command/application/service/BookmarkFolderCommandServiceTests.java
src/test/java/com/runninghi/bookmarkfolder/query/application/service/BookmarkFolderQueryServiceTests.java
src/test/java/com/runninghi/comment/query/application/service/CommentQueryServiceTests.java

[Test] - @BeforeEach 추가

---

src/main/java/com/runninghi/bookmarkfolder/command/application/service/BookmarkFolderCommandService.java
src/main/java/com/runninghi/bookmarkfolder/command/domain/aggregate/entity/BookmarkFolder.java
src/test/java/com/runninghi/bookmarkfolder/command/application/service/BookmarkFolderCommandServiceTests.java

[Refactor] - {BOOKMARK FOLDER} Update  수정

---

src/main/java/com/runninghi/comment/command/application/controller/CommentCommandController.java
src/main/java/com/runninghi/comment/command/application/dto/response/CommentCommandResponse.java
src/main/java/com/runninghi/comment/command/application/dto/response/CommentDeleteResponse.java
src/main/java/com/runninghi/comment/command/application/service/CommentCommandService.java
src/main/java/com/runninghi/comment/query/application/dto/response/CommentQueryResponse.java
src/main/java/com/runninghi/comment/query/application/service/CommentQueryService.java
src/test/java/com/runninghi/comment/command/application/controller/CommentCommandControllerTests.java
src/test/java/com/runninghi/comment/command/application/service/CommentCommandServiceTests.java
src/test/java/com/runninghi/comment/query/application/service/CommentQueryServiceTests.java

[Feature]-{COMMENT} CUD controller 작성

---

src/main/java/com/runninghi/bookmarkfolder/command/application/controller/FolderCommandController.java
src/main/java/com/runninghi/bookmarkfolder/command/application/dto/response/FolderCommandResponse.java
src/main/java/com/runninghi/bookmarkfolder/command/application/dto/response/FolderDeleteResponse.java
src/main/java/com/runninghi/bookmarkfolder/command/application/service/BookmarkFolderCommandService.java
src/main/java/com/runninghi/bookmarkfolder/query/application/dto/response/FolderQueryResponse.java
src/main/java/com/runninghi/bookmarkfolder/query/application/service/BookmarkFolderQueryService.java
src/test/java/com/runninghi/bookmarkfolder/command/application/service/BookmarkFolderCommandServiceTests.java
src/test/java/com/runninghi/bookmarkfolder/command/controller/FolderCommandControllerTests.java
src/test/java/com/runninghi/bookmarkfolder/query/application/service/BookmarkFolderQueryServiceTests.java

[Feature]-{BOOKMARK FOLDER} CUD controller 작성

---

.github/workflows/gradle.yml
.gitignore
build.gradle

* AWS Elastic Beanstalk에 spring cloud config server 배포
* sccs를 통해 민감정보 관리

[Setting] - Spring Cloud Config Server

---

src/main/java/com/runninghi/bookmark/command/application/dto/request/CreateBookmarkRequest.java
src/main/java/com/runninghi/bookmark/command/application/service/BookmarkCommandService.java
src/main/java/com/runninghi/bookmark/command/domain/aggregate/entity/Bookmark.java
src/main/java/com/runninghi/bookmark/command/domain/aggregate/vo/BookmarkUserVO.java
src/main/java/com/runninghi/bookmarkfolder/command/application/dto/request/CreateFolderRequest.java
src/main/java/com/runninghi/bookmarkfolder/command/application/dto/request/UpdateFolderRequest.java
src/main/java/com/runninghi/bookmarkfolder/command/application/dto/response/FolderCommandResponse.java
src/main/java/com/runninghi/bookmarkfolder/command/application/service/BookmarkFolderCommandService.java
src/main/java/com/runninghi/bookmarkfolder/command/domain/aggregate/entity/BookmarkFolder.java
src/main/java/com/runninghi/bookmarkfolder/command/domain/aggregate/vo/FolderUserVO.java
src/main/java/com/runninghi/bookmarkfolder/query/application/dto/response/FolderQueryResponse.java
src/main/java/com/runninghi/comment/command/application/dto/request/CreateCommentRequest.java
src/main/java/com/runninghi/comment/command/application/dto/response/CommentCommandResponse.java
src/main/java/com/runninghi/comment/command/application/service/CommentCommandService.java
src/main/java/com/runninghi/comment/command/domain/aggregate/entity/Comment.java
src/main/java/com/runninghi/comment/command/domain/aggregate/vo/CommentUserVO.java
src/main/java/com/runninghi/comment/query/application/dto/response/CommentQueryResponse.java
src/test/java/com/runninghi/bookmark/command/application/service/BookmarkCommandServiceTests.java
src/test/java/com/runninghi/bookmark/query/application/service/BookmarkQueryServiceTests.java
src/test/java/com/runninghi/bookmarkfolder/command/application/service/BookmarkFolderCommandServiceTests.java
src/test/java/com/runninghi/bookmarkfolder/command/controller/FolderCommandControllerTests.java
src/test/java/com/runninghi/bookmarkfolder/query/application/service/BookmarkFolderQueryServiceTests.java
src/test/java/com/runninghi/comment/command/application/controller/CommentCommandControllerTests.java
src/test/java/com/runninghi/comment/command/application/service/CommentCommandServiceTests.java
src/test/java/com/runninghi/comment/query/application/service/CommentQueryServiceTests.java

[Refactor] - userNo 중간객체 VO 이용

---

src/main/java/com/runninghi/bookmark/command/application/service/BookmarkCommandService.java
src/main/java/com/runninghi/bookmark/command/domain/service/BookmarkCommandDomainService.java
src/main/java/com/runninghi/bookmark/command/infrastructure/service/BookmarkCommandInfraService.java
src/test/java/com/runninghi/bookmark/command/application/service/BookmarkCommandServiceTests.java

[Feature] - {Bookmark} 이미 저장된 즐겨찾기 예외처리

---

build.gradle
src/main/java/com/runninghi/configuration/AwsS3Config.java

* closed #181 
* aws s3 config 설정
* s3 버킷 생성

[Feature] - {AWS S3} aws s3 환경 설정

---

src/main/java/com/runninghi/bookmark/command/application/dto/request/CreateBookmarkRequest.java
src/main/java/com/runninghi/bookmark/command/application/dto/response/BookmarkCommandResponse.java
src/main/java/com/runninghi/bookmark/command/application/dto/response/BookmarkDeleteResponse.java
src/main/java/com/runninghi/bookmark/command/application/service/BookmarkCommandService.java
src/main/java/com/runninghi/bookmark/command/domain/aggregate/entity/Bookmark.java
src/main/java/com/runninghi/bookmarkfolder/command/application/dto/request/CreateFolderRequest.java
src/main/java/com/runninghi/bookmarkfolder/command/application/dto/request/UpdateFolderRequest.java
src/main/java/com/runninghi/bookmarkfolder/command/application/dto/response/FolderCommandResponse.java
src/main/java/com/runninghi/bookmarkfolder/command/application/service/BookmarkFolderCommandService.java
src/main/java/com/runninghi/bookmarkfolder/command/domain/aggregate/entity/BookmarkFolder.java
src/main/java/com/runninghi/bookmarkfolder/query/application/dto/response/FolderQueryResponse.java
src/main/java/com/runninghi/comment/command/application/dto/request/CreateCommentRequest.java
src/main/java/com/runninghi/comment/command/application/dto/response/CommentCommandResponse.java
src/main/java/com/runninghi/comment/command/application/service/CommentCommandService.java
src/main/java/com/runninghi/comment/command/domain/aggregate/entity/Comment.java
src/main/java/com/runninghi/comment/query/application/dto/request/FindAllCommentsRequest.java
src/main/java/com/runninghi/comment/query/application/dto/response/CommentQueryResponse.java
src/main/java/com/runninghi/comment/query/application/service/CommentQueryService.java
src/main/java/com/runninghi/comment/query/infrastructure/repository/CommentQueryRepository.java
src/test/java/com/runninghi/bookmark/command/application/service/BookmarkCommandServiceTests.java
src/test/java/com/runninghi/bookmark/query/application/service/BookmarkQueryServiceTests.java
src/test/java/com/runninghi/bookmarkfolder/command/application/service/BookmarkFolderCommandServiceTests.java
src/test/java/com/runninghi/bookmarkfolder/command/controller/FolderCommandControllerTests.java
src/test/java/com/runninghi/bookmarkfolder/query/application/service/BookmarkFolderQueryServiceTests.java
src/test/java/com/runninghi/comment/command/application/controller/CommentCommandControllerTests.java
src/test/java/com/runninghi/comment/command/application/service/CommentCommandServiceTests.java
src/test/java/com/runninghi/comment/query/application/service/CommentQueryServiceTests.java

* closed #179 
* closed #180 
* closed #185

[Feature] - {Comment} 신고 상태, 업데이트 날짜 엔티티 추가

---

src/main/java/com/runninghi/comment/command/application/dto/response/CommentCommandResponse.java
src/test/java/com/runninghi/comment/command/application/service/CommentCommandServiceTests.java

[Fix]-{COMMENT} command responseDTO  수정

---

src/main/java/com/runninghi/bookmark/command/application/controller/BookmarkCommandController.java
src/main/java/com/runninghi/bookmarkfolder/command/application/controller/FolderCommandController.java
src/main/java/com/runninghi/comment/command/application/controller/CommentCommandController.java
src/main/java/com/runninghi/keyword/command/application/controller/KeywordCommandController.java
src/main/java/com/runninghi/keyword/command/application/dto/request/KeywordUpdateRequest.java
src/main/java/com/runninghi/keyword/command/application/service/KeywordCommandService.java
src/main/java/com/runninghi/keyword/query/application/controller/KeywordQueryController.java
src/main/java/com/runninghi/user/command/application/dto/sign_in/response/SignInResponse.java
src/test/java/com/runninghi/keyword/command/application/service/KeywordCommandServiceTest.java

[Refactoring] - {COMMON} 컨트롤러 태그 명칭 통일 및 키워드 컨트롤러 설계

---

src/main/java/com/runninghi/common/exception/ExceptionResponseHandler.java
src/test/java/com/runninghi/user/command/application/controller/AdminCommandControllerTest.java
src/test/java/com/runninghi/user/command/application/controller/SignCommandControllerTest.java
src/test/java/com/runninghi/user/command/application/controller/UserCommandControllerTest.java
src/test/java/com/runninghi/user/command/application/service/UserCommandServiceTest.java
src/test/java/com/runninghi/user/query/application/controller/AdminQueryControllerTest.java
src/test/java/com/runninghi/user/query/application/controller/SignQueryControllerTest.java
src/test/java/com/runninghi/user/query/application/controller/UserQueryControllerTest.java
src/test/java/com/runninghi/user/query/application/service/AdminQueryServiceTest.java

[BUGFIX] - {USER} USER 테스트 케이스 버그 픽스 

---

src/main/java/com/runninghi/adminpost/command/application/controller/AdminPostCommandController.java
src/main/java/com/runninghi/adminpost/command/application/service/AdminPostCommandService.java
src/main/java/com/runninghi/keyword/command/application/controller/KeywordCommandController.java

* closed #220 
- 관리자 게시글 생성 메소드 문서 주석 작성
- 관리자 여부 확인 메소드 위치 변경

[Refactor]  - {Admin Post}  관리자 여부 판단 위치 변경

---

.gitignore
src/main/java/com/runninghi/bookmark/command/domain/service/ApiBookmarkDomainService.java
src/main/java/com/runninghi/bookmark/command/domain/service/BookmarkCommandDomainService.java
src/main/java/com/runninghi/comment/command/application/service/CommentCommandService.java
src/main/java/com/runninghi/comment/command/domain/service/ApiCommentDomainService.java
src/main/java/com/runninghi/comment/command/domain/service/CommentCommandDomainService.java
src/main/java/com/runninghi/comment/command/infrastructure/service/ApiCommentInfraService.java
src/main/java/com/runninghi/comment/query/application/controller/CommentQueryController.java
src/main/java/com/runninghi/comment/query/application/controller/test.java
src/main/java/com/runninghi/comment/query/application/dto/response/CommentQueryResponse.java
src/main/java/com/runninghi/comment/query/application/service/CommentQueryService.java
src/main/java/com/runninghi/comment/query/infrastructure/repository/CommentQueryRepository.java
src/main/resources/db/data/data.sql
src/test/java/com/runninghi/comment/command/application/service/CommentCommandServiceTests.java
src/test/java/com/runninghi/comment/query/application/service/CommentQueryServiceTests.java

* closed #219 
* closed #223
- Infra, Domain service 구조 수정했습니다. 꼼꼼한 확인 부탁드려용,,,

[Feature] - {Comment} 회원 확인 로직 추가 및 service 리팩토링
